# Generated by Django 5.0.2 on 2024-03-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0011_pantalon_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantalon',
            name='imagenArticulo',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
