# Generated by Django 5.0.2 on 2024-03-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0012_alter_pantalon_imagenarticulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantalon',
            name='imagenArticulo',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
