# Generated by Django 5.0.2 on 2024-03-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0013_alter_pantalon_imagenarticulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='buzo',
            name='imagenArticulo',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AddField(
            model_name='remera',
            name='imagenArticulo',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
