# Generated by Django 5.0.2 on 2024-03-30 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0015_buzo_user_remera_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buzo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pantalon',
            name='user',
        ),
        migrations.RemoveField(
            model_name='remera',
            name='user',
        ),
    ]
